### ISSUE TITLE
M/K v M and K

### ISSUE THREAD

**Issue by aenieblas** [fdiwg/smt-shiny#1]
When entering value of M/K in the LBI tool - this works fine. When entering separately M and K - this gives a non-fatal error :
image
![image](https://user-images.githubusercontent.com/33573363/233297199-3758082a-ba1c-4431-ac00-50e2cd0a805d.png)

The results display correctly, but the report does not download (though the zip file does).

**Comment by aenieblas** [comment]
Hello, trying this again, and this error is still present for the spangled emperor, but seems to be a fatal error now, i.e. no results display:

![image](https://github.com/fdiwg/smt-shiny/assets/33573363/0af02387-4389-422b-ac6c-655d29e6c575)

**Comment by tokami** [comment]
Thanks for catching this. Problem was that Linf > Lmax, but this should be fixed now

**Comment by aenieblas** [comment]
non fatal missing value:T/F error persists with European anchovy, LBI tool when entering M and K separately

![image](https://github.com/fdiwg/smt-shiny/assets/33573363/ad40d3f6-9a79-4484-93ba-e8517e99efc0)
